#! /bin/bash
#Программа для изменеия пространства имен
#у всех файлов заданной директории

homeDir=`pwd`
workDir="src/Hexlet/Arrays"
base="Php\Hexlet\Arrays"

cd $workDir
echo "Changing directory to: $workDir"

listOfFiles=`ls`

for file in $listOfFiles
do
oldNamespace=`grep namespace $file`
#echo $oldNamespace
fileWithoutExt=$(echo $file | sed 's/.php//')
namespace="namespace $base\\$fileWithoutExt"
echo "$oldNamespace ---> $namespace"
escapedNamespace=$(echo $namespace | sed 's!\\!\\\\!g')
sed -i "/namespace/c $escapedNamespace;" $file
done

cd $homeDir
echo "Changing directory to: $homeDir"


workDir="tests/Hexlet/Arrays"
base="Php\Hexlet\Arrays\Tests"

cd $workDir
echo "Changing directory to: $workDir"

listOfFiles=`ls`

for file in $listOfFiles
do
oldNamespace=`grep namespace $file`
fileWithoutExt=$(echo $file | sed 's/.php//')
namespace="namespace $base"
echo "$oldNamespace ---> $namespace"
escapedNamespace=$(echo $namespace | sed 's!\\!\\\\!g')
sed -i "/namespace/c $escapedNamespace;" $file
done

cd $homeDir
echo "Changing directory to: $homeDir"
