#! /bin/bash
#Программа для изменеия пространства имен
#у всех файлов заданной директории

homeDir=`pwd`
workDir="tests/Hexlet/Arrays"
base="Php\Hexlet\Arrays"

cd $workDir
echo "Changing directory to: $workDir"

listOfFiles=`ls`

for file in $listOfFiles
do
oldUse=`grep use $file`

#fileWithoutExt=$(echo $file | sed 's/\.php//')
localNsName=$(echo $file | sed 's/Test\.php//')
funcName="${localNsName,}" 
#newNamespace="namespace $base\\$fileWithoutExt\\$funcName"
#newNamespace="namespace Php\\Hexlet\\Tests"
#echo "Replacing $oldNamespace ---> $newNamespace"
#echo "$localNsName ---> $funcName"
use="use function $base\\$localNsName\\$funcName"
escapedUse=$(echo $use | sed 's!\\!\\\\!g')
sed -i "/use function/c $escapedUse;" $file
echo "Replacing $oldUse ---> $use"
done
cd $homeDir
echo "Changing directory to: $homeDir"

#use PHPUnit\Framework\TestCase;
